const marker_categories = [
  { id: 67, sub_category: "All", category: "All" },
  { id: 1, sub_category: "Restaurants", category: "Food & Drink" },
  { id: 2, sub_category: "Cafes", category: "Food & Drink" },
  { id: 3, sub_category: "Bars", category: "Food & Drink" },
  { id: 4, sub_category: "Fast Food", category: "Food & Drink" },
  { id: 5, sub_category: "Grocery Stores", category: "Food & Drink" },
  { id: 6, sub_category: "Supermarkets", category: "Food & Drink" },
  { id: 7, sub_category: "Hotels", category: "Accommodation" },
  { id: 8, sub_category: "Hostels", category: "Accommodation" },
  { id: 9, sub_category: "Motels", category: "Accommodation" },
  { id: 10, sub_category: "Resorts", category: "Accommodation" },
  { id: 11, sub_category: "Bed & Breakfast", category: "Accommodation" },
  { id: 12, sub_category: "Museums", category: "Culture & Entertainment" },
  {
    id: 13,
    sub_category: "Art Galleries",
    category: "Culture & Entertainment",
  },
  { id: 14, sub_category: "Theaters", category: "Culture & Entertainment" },
  { id: 15, sub_category: "Cinemas", category: "Culture & Entertainment" },
  { id: 16, sub_category: "Parks", category: "Outdoor Activities" },
  { id: 17, sub_category: "Hiking Trails", category: "Outdoor Activities" },
  { id: 18, sub_category: "Beaches", category: "Outdoor Activities" },
  { id: 19, sub_category: "Campgrounds", category: "Outdoor Activities" },
  { id: 20, sub_category: "Gyms", category: "Health & Fitness" },
  { id: 21, sub_category: "Yoga Studios", category: "Health & Fitness" },
  { id: 22, sub_category: "Spas", category: "Health & Fitness" },
  { id: 23, sub_category: "Hospitals", category: "Health & Fitness" },
  { id: 24, sub_category: "Pharmacies", category: "Health & Fitness" },
  { id: 25, sub_category: "Banks", category: "Services" },
  { id: 26, sub_category: "ATMs", category: "Services" },
  { id: 27, sub_category: "Post Offices", category: "Services" },
  { id: 28, sub_category: "Libraries", category: "Education" },
  { id: 29, sub_category: "Schools", category: "Education" },
  { id: 30, sub_category: "Colleges", category: "Education" },
  { id: 31, sub_category: "Universities", category: "Education" },
  { id: 32, sub_category: "Public Transport", category: "Transport" },
  { id: 33, sub_category: "Taxi Stands", category: "Transport" },
  { id: 34, sub_category: "Train Stations", category: "Transport" },
  { id: 35, sub_category: "Bus Stops", category: "Transport" },
  { id: 36, sub_category: "Airports", category: "Transport" },
  { id: 37, sub_category: "Parking Lots", category: "Transport" },
  { id: 38, sub_category: "Shopping Malls", category: "Shopping" },
  { id: 39, sub_category: "Clothing Stores", category: "Shopping" },
  { id: 40, sub_category: "Electronics Stores", category: "Shopping" },
  { id: 41, sub_category: "Bookstores", category: "Shopping" },
  { id: 42, sub_category: "Furniture Stores", category: "Shopping" },
  { id: 43, sub_category: "Hair Salons", category: "Personal Care" },
  { id: 44, sub_category: "Barbershops", category: "Personal Care" },
  { id: 45, sub_category: "Nail Salons", category: "Personal Care" },
  { id: 46, sub_category: "Dry Cleaners", category: "Services" },
  { id: 47, sub_category: "Laundromats", category: "Services" },
  { id: 48, sub_category: "Car Washes", category: "Services" },
  { id: 49, sub_category: "Gas Stations", category: "Services" },
  { id: 50, sub_category: "Car Repair", category: "Services" },
  { id: 51, sub_category: "Churches", category: "Religious Sites" },
  { id: 52, sub_category: "Mosques", category: "Religious Sites" },
  { id: 53, sub_category: "Temples", category: "Religious Sites" },
  { id: 54, sub_category: "Synagogues", category: "Religious Sites" },
  { id: 55, sub_category: "Courthouses", category: "Government Buildings" },
  { id: 56, sub_category: "City Halls", category: "Government Buildings" },
  {
    id: 57,
    sub_category: "Police Stations",
    category: "Government Buildings",
  },
  { id: 58, sub_category: "Fire Stations", category: "Government Buildings" },
  { id: 59, sub_category: "Embassies", category: "Government Buildings" },
  { id: 60, sub_category: "Zoos", category: "Attractions" },
  { id: 61, sub_category: "Aquariums", category: "Attractions" },
  { id: 62, sub_category: "Theme Parks", category: "Attractions" },
  { id: 63, sub_category: "Historic Sites", category: "Attractions" },
  { id: 64, sub_category: "Monuments", category: "Attractions" },
  { id: 65, sub_category: "Botanical Gardens", category: "Attractions" },
];

export default marker_categories;
